# docker-compose.yml
version: '1'
services:
  consul:
    image: hashicorp/consul
    ports:
      - "8500:8500"  # Consul UI


  application_api_0:
    image: application_api:latest
    ports:
      - "10001:5000"

  application_api_1:
    image: application_api:latest
    ports:
      - "10002:5000"

  application_api_2:
    image: application_api:latest
    ports:
      - "10003:5000"


  routing_api:
    image: routing_api:latest
    ports:
      - "20001:5000"
    env_file:
      - config.env  # Reference the sid.env file for this service
    environment:
      - SLOW_DOWN_THRESHOLD_MS = ${SLOW_DOWN_THRESHOLD_MS}
      - APP_API_TIMEOUT_MS = ${APP_API_TIMEOUT_MS}
      - ENV = ${ENV}